# Coding Self-Attention in PyTroch!!!


In [1]:
import torch ## torch let's us create tensors and also provides helper functions
import torch.nn as nn ## torch.nn gives us nn.module() and nn.Linear()
import torch.nn.functional as F # This gives us the softmax()

/home/porya/Desktop/HandsonLLMs/.LLM_venv/lib/python3.12/site-packages/torch/_subclasses/functional_tensor.py:279: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


In [11]:
class SelfAttention(nn.Module):
    def __init__(self, d_model=2, row_dim=0, column_dim=1):
        super().__init__()

        self.W_q = nn.Linear(in_features = d_model,
                             out_features= d_model,
                             bias=False)
        self.W_k = nn.Linear(in_features= d_model,
                             out_features= d_model,
                             bias=False)
        self.W_v = nn.Linear(in_features= d_model,
                             out_features= d_model,
                             bias=False)
        
        self.row_dim = row_dim
        self.column_dim = column_dim

    def forward(self, token_encoding):
        q= self.W_q(token_encoding)
        k= self.W_k(token_encoding)
        v= self.W_v(token_encoding)

        sims = torch.matmul(q, k.transpose(dim0=self.row_dim,
                                           dim1=self.column_dim))
        scaled_sims = sims / torch.tensor(k.size(self.column_dim)**0.5)
        attention_percents = F.softmax(scaled_sims, dim=self.column_dim)
        attention_scores = torch.matmul(attention_percents, v)

        return attention_scores


In [ ]:
encoding_matrix = torch.tensor([[1.16, 0.23],
                                [0.57, 1.36],
                                [4.41, -2.16]])
print(f"encoding_matrix:\n ",encoding_matrix)

torch.manual_seed(42)
selfAttention = SelfAttention(d_model=2, row_dim=0, column_dim=1)

selfAttention(encoding_matrix)

encoding_matrix:
  tensor([[ 1.1600,  0.2300],
        [ 0.5700,  1.3600],
        [ 4.4100, -2.1600]])


tensor([[1.0100, 1.0641],
        [0.2040, 0.7057],
        [3.4989, 2.2427]], grad_fn=<MmBackward0>)

In [14]:
selfAttention.W_q.weight.transpose(0,1)

tensor([[ 0.5406, -0.1657],
        [ 0.5869,  0.6496]], grad_fn=<TransposeBackward0>)

# Coding Masked Self-Attention in PyTroch!!!


In [ ]:
import torch ## torch let's us create tensors and also provides helper functions
import torch.nn as nn ## torch.nn gives us nn.module() and nn.Linear()
import torch.nn.functional as F # This gives us the softmax()

In [17]:
class MaskedSelfAttention(nn.Module):
    def __init__(self, d_model=2, row_dim=0, column_dim=1):
        super().__init__()

        self.W_q = nn.Linear(in_features = d_model,
                             out_features= d_model,
                             bias=False)
        self.W_k = nn.Linear(in_features= d_model,
                             out_features= d_model,
                             bias=False)
        self.W_v = nn.Linear(in_features= d_model,
                             out_features= d_model,
                             bias=False)
        
        self.row_dim = row_dim
        self.column_dim = column_dim

    def forward(self, token_encoding, mask=None):
        q = self.W_q(token_encoding)
        k = self.W_k(token_encoding)
        v = self.W_v(token_encoding)

        sims = torch.matmul(q, k.transpose(dim0=self.row_dim,
                                           dim1=self.column_dim))
        
        scaled_sims = sims / torch.tensor(k.size(self.column_dim)**0.5)
        if mask is not None:
            scaled_sims = scaled_sims.masked_fill(mask=mask,
                                                  value=-1e9)

        attention_percents = F.softmax(scaled_sims, dim=self.column_dim)
        attention_scores = torch.matmul(attention_percents, v)

        return attention_scores


In [ ]:
encoding_matrix = torch.tensor([[1.16, 0.23],
                                [0.57, 1.36],
                                [4.41, -2.16]])
print(f"encoding_matrix:\n ",encoding_matrix)

torch.manual_seed(42)
maskedSelfAttention = MaskedSelfAttention(d_model=2, row_dim=0, column_dim=1)
mask = torch.tril(torch.ones(3,3))
mask=mask==0

maskedSelfAttention(encoding_matrix, mask)

encoding_matrix:
  tensor([[ 1.1600,  0.2300],
        [ 0.5700,  1.3600],
        [ 4.4100, -2.1600]])


tensor([[ 0.6038,  0.7434],
        [-0.0062,  0.6072],
        [ 3.4989,  2.2427]], grad_fn=<MmBackward0>)